// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNSyK81yAh5uZip_TPG6S6BBqqL3t33n0',
    appId: '1:251732615818:web:cb1f0de775c877e3b54373',
    messagingSenderId: '251732615818',
    projectId: 'firstproject-1572b',
    authDomain: 'firstproject-1572b.firebaseapp.com',
    storageBucket: 'firstproject-1572b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWIz6qZSnlL7MgwnT7b4SVlg5LjrlYxw',
    appId: '1:251732615818:android:a4118aae90c3bc9cb54373',
    messagingSenderId: '251732615818',
    projectId: 'firstproject-1572b',
    storageBucket: 'firstproject-1572b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhU7JFT99kLAI350gSoiembbn_owB7MgQ',
    appId: '1:251732615818:ios:b3ac156da437ebc1b54373',
    messagingSenderId: '251732615818',
    projectId: 'firstproject-1572b',
    storageBucket: 'firstproject-1572b.appspot.com',
    iosClientId: '251732615818-i7i3ht1qbkufbg1vpcffipqn45gtnsto.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhU7JFT99kLAI350gSoiembbn_owB7MgQ',
    appId: '1:251732615818:ios:b3ac156da437ebc1b54373',
    messagingSenderId: '251732615818',
    projectId: 'firstproject-1572b',
    storageBucket: 'firstproject-1572b.appspot.com',
    iosClientId: '251732615818-i7i3ht1qbkufbg1vpcffipqn45gtnsto.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
